title: Ty Hayes, SRSE
description: An example site for PhD students wanting to use GitHub Pages
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

